management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
        exclude:
        - env
logging:
  level:
    root: WARN
    com.maqs: DEBUG
    org.springframework: INFO
server:
  port: 9999
  connection-timeout: -1
  servlet:
    context-path: /reports